using MediatR;
using Microsoft.EntityFrameworkCore;
using SalesDesk.Application.Billing;
using SalesDesk.Application.Common.Interfaces;
using SalesDesk.Application.Documents;
using SalesDesk.Domain.Documents;

namespace SalesDesk.Application.Recurring;

/// <summary>
/// The recurring-retainer engine's single entry point (VERSION-2 roadmap item 3),
/// invoked periodically by the Infrastructure-layer background service — mirrors
/// <c>DispatchDueRemindersCommand</c>'s shape. Generates one new Draft (or
/// dispatched, per <see cref="RecurringSchedule.AutoDispatch"/>) Document for every
/// active schedule whose <see cref="RecurringSchedule.NextRunDate"/> has come due,
/// copies the schedule's line items onto it, then advances the schedule past today.
/// Returns the number of documents actually generated.
/// </summary>
public sealed record GenerateDueRecurringDocumentsCommand : IRequest<int>;

public sealed class GenerateDueRecurringDocumentsCommandHandler(
    IApplicationDbContext context, IDateTime dateTime, IEmailSender emailSender, IPublicLinkBuilder linkBuilder)
    : IRequestHandler<GenerateDueRecurringDocumentsCommand, int>
{
    public async Task<int> Handle(GenerateDueRecurringDocumentsCommand request, CancellationToken cancellationToken)
    {
        var now = dateTime.UtcNow.UtcDateTime;
        var today = DateOnly.FromDateTime(now);

        var dueSchedules = await context.RecurringSchedules
            .Include(s => s.LineItems)
            .Where(s => s.IsActive && s.NextRunDate <= today)
            .ToListAsync(cancellationToken);

        if (dueSchedules.Count == 0)
        {
            return 0;
        }

        var workspaceIds = dueSchedules.Select(s => s.WorkspaceId).Distinct().ToList();
        var workspacesById = await context.Workspaces
            .Where(w => workspaceIds.Contains(w.Id))
            .ToDictionaryAsync(w => w.Id, cancellationToken);

        var generatedCount = 0;

        foreach (var schedule in dueSchedules)
        {
            if (!workspacesById.TryGetValue(schedule.WorkspaceId, out var workspace) || !workspace.IsActive)
            {
                continue;
            }

            // Same effective-limit rule as CreateDocumentCommand (VERSION-2 quota
            // reconciliation): an admin override wins outright, else the
            // subscription tier's own monthly limit applies. A schedule that would
            // push a workspace over its limit is simply skipped this run — its
            // NextRunDate is left untouched, so the next sweep retries it
            // automatically, which naturally succeeds once the calendar month
            // rolls over and the workspace's document count resets.
            var monthlyLimit = workspace.DocumentQuota ?? PricingCatalog.MonthlyDocumentLimit(workspace.SubscriptionTier);
            if (monthlyLimit is not null)
            {
                var monthStart = new DateOnly(today.Year, today.Month, 1);
                var issuedThisMonth = await context.Documents
                    .CountAsync(d => d.WorkspaceId == schedule.WorkspaceId && d.IssueDate >= monthStart, cancellationToken);

                if (issuedThisMonth >= monthlyLimit)
                {
                    continue;
                }
            }

            var customer = await context.Customers.FirstOrDefaultAsync(c => c.Id == schedule.CustomerId, cancellationToken);
            var template = await context.Templates.FirstOrDefaultAsync(t => t.Id == schedule.TemplateId, cancellationToken);
            if (customer is null || template is null)
            {
                // Referential integrity is enforced (Restrict) so neither can be
                // deleted out from under an active schedule — this is a defensive
                // skip, not an expected path.
                continue;
            }

            var documentNumber = await DocumentNumbering.GenerateNextAsync(context, schedule.WorkspaceId, schedule.Type, today, cancellationToken);
            var document = new Document(
                schedule.WorkspaceId, documentNumber, schedule.Type, customer.Id, template.Id,
                today, today.AddDays(schedule.DueDateOffsetDays), schedule.Currency, schedule.ClientCountry);

            foreach (var item in schedule.LineItems)
            {
                document.AddLineItem(item.Description, item.Quantity, item.UnitPrice, item.ProductId);
            }

            context.DocumentActivities.Add(document.RecordActivity(DocumentActivityType.Created, "Generated by a recurring schedule.", now));

            if (schedule.AutoDispatch)
            {
                document.Dispatch(now);
                context.DocumentActivities.Add(document.Activities.Last());
            }

            template.RecordUsage();
            context.Documents.Add(document);

            // Skip past any periods missed while the schedule was paused or the
            // app was down, rather than backfilling one document per missed
            // period — a retainer schedule catches up to "due again next period,"
            // it doesn't dump a stack of overdue invoices on the client at once.
            var nextRun = schedule.Interval.AddTo(schedule.NextRunDate);
            while (nextRun <= today)
            {
                nextRun = schedule.Interval.AddTo(nextRun);
            }

            schedule.RecordRun(nextRun);

            // Saved per-schedule (not batched until the end of the run) so a
            // mid-run crash can't cause an already-generated document to be
            // generated again on the next tick — same reasoning as
            // DispatchDueRemindersCommand's per-send save.
            await context.SaveChangesAsync(cancellationToken);

            if (schedule.AutoDispatch)
            {
                // DocumentDispatchNotifier needs the Customer navigation populated
                // (the just-saved `document` only has CustomerId set) — same reload
                // CreateDocumentCommandHandler does before its own dispatch notify.
                var withCustomer = await context.Documents
                    .Include(d => d.Customer)
                    .FirstAsync(d => d.Id == document.Id, cancellationToken);
                await DocumentDispatchNotifier.NotifyAsync(context, emailSender, linkBuilder, withCustomer, schedule.WorkspaceId, cancellationToken);
            }

            generatedCount++;
        }

        return generatedCount;
    }
}
